name: Config deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install git-ftp
        run: |
          curl -LJO https://raw.githubusercontent.com/git-ftp/git-ftp/1.6.0/git-ftp > git-ftp
          chmod 755 git-ftp
        shell: bash

      - name: Configure git-ftp
        run: |
          git config --global user.email "agentfox@fab5.team"
          git config --global user.name "Agent Fox"
          git config git-ftp.url "ftp://89.46.223.232:21/89.46.223.232_27015/csgo/"
          git config git-ftp.user "$FTP_USER"
          git config git-ftp.password "$FTP_PASS"
          git config git-ftp.insecure 1
          git config git-ftp.disable-epsv 1
          git config git-ftp.syncroot .
        shell: bash
        env:
          # FTP_ADDR: ${{ secrets.FTP_SERVER }}
          # FTP_ROOT: ${{ secrets.FTP_ROOT_DIR }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}

      - name: Deploy
        run: git ftp push -v
        shell: bash

